### ISSUE TITLE
Hardcoded path breaks Buildship

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-umbrella#16]
In /xtext-umbrella/gradle-composite/build.gradle there are hardcoded path entries to `../xtext-umbrella/releng/`

`xtext-umbrella` is not the project name but the git root directory which can be different depending on user configuration used during the Ommph setup.

Buildship stops resolution with:
```
Caused by: org.gradle.api.InvalidUserDataException: Project directory '/Users/dhuebner/git/xtext-umbrella/releng/gradle-composite' does not exist.
	at org.gradle.initialization.ProjectDirectoryProjectSpec.checkPreconditions(ProjectDirectoryProjectSpec.java:52)
	at org.gradle.initialization.AbstractProjectSpec.containsProject(AbstractProjectSpec.java:27)
	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:51)
	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:48)
	at org.gradle.initialization.NotifyingSettingsLoader.findAndLoadSettings(NotifyingSettingsLoader.java:33)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:147)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	... 44 more```

**Comment by cdietrich** [comment]
i have no idea how to guess that name
@oehme do you have an idea?

**Comment by oehme** [comment]
Just insert the absolute path.

**Comment by cdietrich** [comment]
yes but how do i get that?

**Comment by cdietrich** [comment]
something like

```
task('generatePrefs') {
    doLast {
        def base = file(".").absolutePath
        println(base)
        file('../../../').listFiles()
        .findAll { file ->
            file.isDirectory() && XTEXT_GRADLE_PROJECTS.any{p->file.name.contains(p)} && new File(file, "settings.gradle").exists()
        }.each { file -> 
            println  "generating buildship prefs for " + file.path
            if (!(new File(file, '.settings')).exists()) {
                new File(file, '.settings').mkdir();
            }
            (new File(file, '.settings/org.eclipse.buildship.core.prefs')).text = "connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)\nconnection.project.dir="+base+"\nproject.path=\\:"+file.name+"\n"
                    
            file.listFiles().each { File fx -> 
                if (fx.isDirectory() && new File(fx, "build.gradle").exists()) {
                    println  "generating buildship prefs for " + fx.path
                    if (!(new File(fx, '.settings')).exists()) {
                        new File(fx, '.settings').mkdir();
                    }
                    (new File(fx, '.settings/org.eclipse.buildship.core.prefs')).text = "connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)\nconnection.project.dir="+base+"\nproject.path=\\:"+fx.name+"\n"
                    }

                }
            }
    }
}
```

@dhuebner can you test?

**Comment by cdietrich** [comment]
@oehme how does the path to be like on windows? do we have somebody who can test it?

**Comment by oehme** [comment]
You are looking for `rootDir`

**Comment by cdietrich** [comment]
I am searching the dir where the build.gradle that contains the task is defined in

**Comment by cdietrich** [comment]
I'll give a try

**Comment by oehme** [comment]
> build.gradle that contains the task is defined in

It has nothing to do with the build.gradle file. You want the path of the composite root project.

**Comment by cdietrich** [comment]
seems to work on windows as well.

**Comment by dhuebner** [comment]
@cdietrich new File("../../").parent.name will give you the gitroot folder `xtext-umbrella` or what ever

**Comment by cdietrich** [comment]
i still cannot follow you. does the solution in my pull request work for you or does it not
